### ISSUE TITLE
Seems as if NetBeast is abandoned

### ISSUE THREAD

**Issue by swilson86** [netbeast/node-red-contrib-netbeast#3]
I have not been able to get NetBeast working. Installing it seems to load node-red with about 275 updates, most of which I have no idea why. The entire project seems to be a mess and nobody has responded or written anything in about 1-1/2 years. I wish I had not installed it... those 275 updates did not seem to screw up anything, but still I don't like it.

I am hesitant to uninstall NetBeast as I don't want to go back to day 1 and reinstall everything else from scratch. Anyone have experience in uninstalling NetBeast? Ideas welcomed!

**Comment by jsdario** [comment]
The Netbeast Dashboard project was indeed, discontinued: https://github.com/netbeast/dashboard

The team and I moved on to create [Yeti Smart Home](https://getyeti.co) as it was too difficult to monetize and keep the machinery working.

To control devices in an open source way we started a documentation / toolbelt project called Bigfoot, so you can connect things to Yeti, but it is still a little bit green https://github.com/netbeast/bigfoot

If you'd like to keep using this node-red module, please feel free to submit a PR. This repo has been long time without commits, so i guess that's why it launches 275 updates.

Sorry for the trouble, I hope this helps.
